name: HassOS-AutoBuild

on:
#  release:
#    types: [published]
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - 'start'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:
  validate_release:
    name: Validate release
    runs-on: [ "ubuntu-20.04" ]
    outputs:
      version: ${{ steps.version_check.outputs.version }}
      version_dev: ${{ steps.version_check.outputs.version_dev }}
    steps:
      - name: detemine ref
        id: detemine_ref
        run: |
          mkdir hassos && cd hassos
          getver=$(wget -qO- -t1 -T2 "https://api.github.com/repos/home-assistant/operating-system/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g' )
          tag_major=$(echo "${getver}" | cut -d '.' -f 1)
          tag_build=$(echo "${getver}" | cut -d '.' -f 2)
          tag_dev=$(echo "${getver}" | cut -d '.' -f 3)
          tag_rel="rel-"${tag_major}
          echo "tag_major=$tag_major" >> $GITHUB_ENV
          echo "tag_build=$tag_build" >> $GITHUB_ENV
          echo "tag_dev=$tag_dev" >> $GITHUB_ENV
          echo "tag_rel=$tag_rel" >> $GITHUB_ENV
          echo ${tag_major}
          echo ${tag_build}
          echo ${tag_dev}
          echo ${tag_rel}
          if [ "" != "$(echo "${{github.event.inputs.ssh}}" | grep fal)" ]; then
            echo "fal"
          fi
          echo ${nproc}
          echo $(nproc)
          cd /etc
          ls -l


